export interface CountryInfo {
  name: string;
  code: string;
  lat: number;
  lng: number;
  zoom: number;
  tagline: string;
  region: string;
}

export const COUNTRIES: CountryInfo[] = [
  { name: "Afghanistan", code: "AF", lat: 33.9391, lng: 67.7100, zoom: 5, tagline: "Heart of the Silk Road", region: "Asia" },
  { name: "Albania", code: "AL", lat: 41.1533, lng: 20.1683, zoom: 7, tagline: "The Last Pristine European Shore", region: "Europe" },
  { name: "Algeria", code: "DZ", lat: 28.0339, lng: 1.6596, zoom: 5, tagline: "Gateway to the Great Sahara", region: "Africa" },
  { name: "Andorra", code: "AD", lat: 42.5063, lng: 1.5218, zoom: 10, tagline: "High Peaks of the Pyrenees", region: "Europe" },
  { name: "Angola", code: "AO", lat: -11.2027, lng: 17.8739, zoom: 5, tagline: "Jewel of Southern Africa", region: "Africa" },
  { name: "Antigua and Barbuda", code: "AG", lat: 17.0608, lng: -61.7964, zoom: 9, tagline: "365 Beaches of Pure Serenity", region: "Caribbean" },
  { name: "Argentina", code: "AR", lat: -38.4161, lng: -63.6167, zoom: 4, tagline: "Land of Fire and Passionate Tango", region: "South America" },
  { name: "Armenia", code: "AM", lat: 40.0691, lng: 45.0382, zoom: 7, tagline: "Ancient Monasteries and Rugged Trails", region: "Europe" },
  { name: "Australia", code: "AU", lat: -25.2744, lng: 133.7751, zoom: 4, tagline: "The Sun-Drenched Great Southern Land", region: "Oceania" },
  { name: "Austria", code: "AT", lat: 47.5162, lng: 14.5501, zoom: 6, tagline: "Imperial Symphonies and Alpine Trails", region: "Europe" },
  { name: "Azerbaijan", code: "AZ", lat: 40.1431, lng: 47.5769, zoom: 7, tagline: "The Land of Eternal Flames", region: "Europe" },
  { name: "Bahamas", code: "BS", lat: 25.0343, lng: -77.3963, zoom: 7, tagline: "Crystal Depths and Coral Sands", region: "Caribbean" },
  { name: "Bahrain", code: "BH", lat: 26.0667, lng: 50.5577, zoom: 9, tagline: "Modern Cityscapes on Ancient Dilmun", region: "Middle East" },
  { name: "Bangladesh", code: "BD", lat: 23.6850, lng: 90.3563, zoom: 6, tagline: "Lush Delta of the Sundarbans", region: "Asia" },
  { name: "Barbados", code: "BB", lat: 13.1939, lng: -59.5432, zoom: 10, tagline: "The Platinum Coastline of the Antilles", region: "Caribbean" },
  { name: "Belarus", code: "BY", lat: 53.7098, lng: 27.9534, zoom: 6, tagline: "Historic Cathedrals and Endless Forests", region: "Europe" },
  { name: "Belgium", code: "BE", lat: 50.5039, lng: 4.4699, zoom: 7, tagline: "Gothic Spires and Masterful Culinary Craft", region: "Europe" },
  { name: "Belize", code: "BZ", lat: 17.1899, lng: -88.4976, zoom: 8, tagline: "The Great Blue Hole and Ancient Maya Forests", region: "Central America" },
  { name: "Benin", code: "BJ", lat: 9.3077, lng: 2.3158, zoom: 6, tagline: "Cradle of West African Heritage", region: "Africa" },
  { name: "Bhutan", code: "BT", lat: 27.5142, lng: 90.4336, zoom: 7, tagline: "Kingdom of Cloud-Kissed Dzongs", region: "Asia" },
  { name: "Bolivia", code: "BO", lat: -16.2902, lng: -63.5887, zoom: 5, tagline: "Mirror of the Sky: Uyuni Salt Flats", region: "South America" },
  { name: "Bosnia and Herzegovina", code: "BA", lat: 43.9159, lng: 17.6791, zoom: 7, tagline: "Where East and West Coexist gracefully", region: "Europe" },
  { name: "Botswana", code: "BW", lat: -22.3285, lng: 24.6849, zoom: 5, tagline: "Unspoiled Wilderness of the Okavango", region: "Africa" },
  { name: "Brazil", code: "BR", lat: -14.2350, lng: -51.9253, zoom: 4, tagline: "Rhythmic Carnivals and Lush Amazonian Canopies", region: "South America" },
  { name: "Brunei", code: "BN", lat: 4.5353, lng: 114.7277, zoom: 8, tagline: "Gilded Domes in the Heart of Borneo", region: "Southeast Asia" },
  { name: "Bulgaria", code: "BG", lat: 42.7339, lng: 25.4858, zoom: 6, tagline: "The Fragrant Valley of Roses", region: "Europe" },
  { name: "Burkina Faso", code: "BF", lat: 12.2383, lng: -1.5616, zoom: 6, tagline: "Lively Melodies of West African Arts", region: "Africa" },
  { name: "Burundi", code: "BI", lat: -3.3731, lng: 29.9189, zoom: 8, tagline: "Glistening Shores of Lake Tanganyika", region: "Africa" },
  { name: "Cabo Verde", code: "CV", lat: 16.0021, lng: -24.0132, zoom: 7, tagline: "Volcanic Archipelago of Morabeza Soul", region: "Africa" },
  { name: "Cambodia", code: "KH", lat: 12.5657, lng: 104.9910, zoom: 6, tagline: "The Mystical Temples of Angkor Wat", region: "Southeast Asia" },
  { name: "Cameroon", code: "CM", lat: 7.3697, lng: 12.3547, zoom: 5, tagline: "Africa in Miniature Landscapes", region: "Africa" },
  { name: "Canada", code: "CA", lat: 56.1304, lng: -106.3468, zoom: 3, tagline: "Boreal Wilds and Glacial Fjords", region: "North America" },
  { name: "Central African Republic", code: "CF", lat: 6.6111, lng: 20.9394, zoom: 5, tagline: "Heartland of Congo Basin Wildlife", region: "Africa" },
  { name: "Chad", code: "TD", lat: 15.4542, lng: 18.7322, zoom: 5, tagline: "Oases and Deserts of Outer Tibesti", region: "Africa" },
  { name: "Chile", code: "CL", lat: -35.6751, lng: -71.5430, zoom: 4, tagline: "Fiery Volcanoes and Ice Fields of Patagonia", region: "South America" },
  { name: "China", code: "CN", lat: 35.8617, lng: 104.1954, zoom: 4, tagline: "Dynastic Wonders and Bamboo Forests", region: "Asia" },
  { name: "Colombia", code: "CO", lat: 4.5709, lng: -72.9565, zoom: 5, tagline: "The Golden Trails of Cocora Palms", region: "South America" },
  { name: "Comoros", code: "KM", lat: -11.8750, lng: 43.8722, zoom: 8, tagline: "The Perfumed Volcanic Isles", region: "Africa" },
  { name: "Costa Rica", code: "CR", lat: 9.7489, lng: -83.7534, zoom: 7, tagline: "Pristine Pura Vida Rainforests", region: "Central America" },
  { name: "Croatia", code: "HR", lat: 45.1000, lng: 15.2000, zoom: 6, tagline: "The Sapphire Sea of a Thousand Islands", region: "Europe" },
  { name: "Cuba", code: "CU", lat: 21.5218, lng: -77.7812, zoom: 6, tagline: "Vintage Cadillacs and Pastel Streets", region: "Caribbean" },
  { name: "Cyprus", code: "CY", lat: 35.1264, lng: 33.4299, zoom: 8, tagline: "The Mythical Birthplace of Aphrodite", region: "Europe" },
  { name: "Czech Republic", code: "CZ", lat: 49.8175, lng: 15.4730, zoom: 6, tagline: "Spire-Studded Castles and Bohemian Culture", region: "Europe" },
  { name: "Denmark", code: "DK", lat: 56.2639, lng: 9.5018, zoom: 6, tagline: "Charming Castles and Waterfront Hygge", region: "Europe" },
  { name: "Djibouti", code: "DJ", lat: 11.8251, lng: 42.5903, zoom: 8, tagline: "Canyons and Hypersaline Lake Assal", region: "Africa" },
  { name: "Dominica", code: "DM", lat: 15.4150, lng: -61.3710, zoom: 9, tagline: "The Untamed Nature Island", region: "Caribbean" },
  { name: "Dominican Republic", code: "DO", lat: 18.7357, lng: -70.1627, zoom: 7, tagline: "Swaying Palms and Golden Shorelines", region: "Caribbean" },
  { name: "Ecuador", code: "EC", lat: -1.8312, lng: -78.1834, zoom: 6, tagline: "Enchanted Isles of the Galápagos", region: "South America" },
  { name: "Egypt", code: "EG", lat: 26.8206, lng: 30.8025, zoom: 5, tagline: "Ancient Pyramids of Giza by the Nile", region: "North Africa" },
  { name: "El Salvador", code: "SV", lat: 13.7942, lng: -88.8965, zoom: 8, tagline: "Volcanic Lagoons and Surfers' Waves", region: "Central America" },
  { name: "Equatorial Guinea", code: "GQ", lat: 1.6508, lng: 10.2679, zoom: 7, tagline: "Spanish Colonial Elegance in Bioko Rainforests", region: "Africa" },
  { name: "Eritrea", code: "ER", lat: 15.1794, lng: 39.7823, zoom: 6, tagline: "Art Deco Masterpieces of Asmara", region: "Africa" },
  { name: "Estonia", code: "EE", lat: 58.5953, lng: 25.0136, zoom: 6, tagline: "Medieval Spires and Digital Landscapes", region: "Europe" },
  { name: "Eswatini", code: "SZ", lat: -26.5225, lng: 31.4659, zoom: 8, tagline: "Lively Culture of the Ezulwini Valley", region: "Africa" },
  { name: "Ethiopia", code: "ET", lat: 9.1450, lng: 40.4897, zoom: 5, tagline: "Rock-Hewn Churches of Lalibela Heritage", region: "Africa" },
  { name: "Fiji", code: "FJ", lat: -17.7134, lng: 178.0650, zoom: 7, tagline: "Warm Welcomes in the Soft Coral Capital", region: "Oceania" },
  { name: "Finland", code: "FI", lat: 61.9241, lng: 25.7482, zoom: 5, tagline: "Midnight Sun over the Thousand Lakes", region: "Europe" },
  { name: "France", code: "FR", lat: 46.2276, lng: 2.2137, zoom: 5, tagline: "High-Fashion, Art, and Epicurean Vineyards", region: "Europe" },
  { name: "Gabon", code: "GA", lat: -0.8037, lng: 11.6094, zoom: 6, tagline: "The Last Eden of West Africa Safari", region: "Africa" },
  { name: "Gambia", code: "GM", lat: 13.4432, lng: -15.3101, zoom: 8, tagline: "Birdwatcher's Paradise beside the River", region: "Africa" },
  { name: "Georgia", code: "GE", lat: 42.3154, lng: 43.3569, zoom: 7, tagline: "Historic Spas and High Caucasian Towns", region: "Europe" },
  { name: "Germany", code: "DE", lat: 51.1657, lng: 10.4515, zoom: 5, tagline: "Castles, Modern Cities, and Fairytale Woods", region: "Europe" },
  { name: "Ghana", code: "GH", lat: 7.9465, lng: -1.0232, zoom: 6, tagline: "The Resonant Gold Coast Hospitality", region: "Africa" },
  { name: "Greece", code: "GR", lat: 39.0742, lng: 21.8243, zoom: 6, tagline: "Mythical ruins above the Aegean Waves", region: "Europe" },
  { name: "Grenada", code: "GD", lat: 12.1165, lng: -61.6790, zoom: 9, tagline: "The Intoxicating Spice Island", region: "Caribbean" },
  { name: "Guatemala", code: "GT", lat: 15.7835, lng: -90.2308, zoom: 7, tagline: "Heart of the Ancient Mayan Empire", region: "Central America" },
  { name: "Guinea", code: "GN", lat: 9.9456, lng: -9.6966, zoom: 6, tagline: "Sources of Magnificent Rivers and Plateaus", region: "Africa" },
  { name: "Guinea-Bissau", code: "GW", lat: 11.8037, lng: -15.1804, zoom: 8, tagline: "Bijagós Isles of Sacred Sea Turtles", region: "Africa" },
  { name: "Guyana", code: "GY", lat: 4.8604, lng: -58.9302, zoom: 6, tagline: "The Roaring Kaieteur Falls Wilderness", region: "South America" },
  { name: "Haiti", code: "HT", lat: 18.9712, lng: -72.6948, zoom: 7, tagline: "Rich Heritage and Mountains of the Citadel", region: "Caribbean" },
  { name: "Honduras", code: "HN", lat: 15.1999, lng: -86.2419, zoom: 7, tagline: "Coral Gardens of Roatan and Copán Ruins", region: "Central America" },
  { name: "Hungary", code: "HU", lat: 47.1625, lng: 19.5033, zoom: 6, tagline: "Grand Thermal Palaces on the Blue Danube", region: "Europe" },
  { name: "Iceland", code: "IS", lat: 64.9631, lng: -19.0208, zoom: 5, tagline: "The Volcanic Forge of Geysers and Northern Lights", region: "Europe" },
  { name: "India", code: "IN", lat: 20.5937, lng: 78.9629, zoom: 4, tagline: "A Vibrant Tapestry of Culture, Heritage, and Color", region: "Asia" },
  { name: "Indonesia", code: "ID", lat: -0.7893, lng: 113.9213, zoom: 4, tagline: "The Enchanted Emerald Archipelago", region: "Southeast Asia" },
  { name: "Iran", code: "IR", lat: 32.4279, lng: 53.6880, zoom: 5, tagline: "Gilded Domes and Persian Poetry", region: "Middle East" },
  { name: "Iraq", code: "IQ", lat: 33.2232, lng: 43.6793, zoom: 6, tagline: "The Cradle of Ancient Mesopotamia", region: "Middle East" },
  { name: "Ireland", code: "IE", lat: 53.4129, lng: -8.2439, zoom: 6, tagline: "Emerald Cliffs and Warm Fireside Melodies", region: "Europe" },
  { name: "Israel", code: "IL", lat: 31.0461, lng: 34.8516, zoom: 7, tagline: "Ancient Walls and Mediterranean Cafes", region: "Middle East" },
  { name: "Italy", code: "IT", lat: 41.8719, lng: 12.5674, zoom: 5, tagline: "Ancient Coliseums, Majestic Lakes, and Culinary Masterpieces", region: "Europe" },
  { name: "Jamaica", code: "JM", lat: 18.1096, lng: -77.2975, zoom: 8, tagline: "Reggae Rhythms and Golden Shorelines", region: "Caribbean" },
  { name: "Japan", code: "JP", lat: 36.2048, lng: 138.2529, zoom: 5, tagline: "Timeless Zen Temples and Neon Cityscapes", region: "Asia" },
  { name: "Jordan", code: "JO", lat: 31.2400, lng: 36.5100, zoom: 7, tagline: "The Rose-Red Majesty of Petra Corners", region: "Middle East" },
  { name: "Kazakhstan", code: "KZ", lat: 48.0196, lng: 66.9237, zoom: 4, tagline: "Steppes and Alpine Charyn Canyons", region: "Asia" },
  { name: "Kenya", code: "KE", lat: -0.0236, lng: 37.9062, zoom: 5, tagline: "Swaying Grasses of the Masai Mara Horizon", region: "Africa" },
  { name: "Kiribati", code: "KI", lat: -3.3704, lng: -168.7340, zoom: 4, tagline: "Pacific Atolls Where the Day First Dawns", region: "Oceania" },
  { name: "Kuwait", code: "KW", lat: 29.3759, lng: 47.9774, zoom: 8, tagline: "Sleek Gilded Towers of the Persian Gulf", region: "Middle East" },
  { name: "Kyrgyzstan", code: "KG", lat: 41.2044, lng: 74.7661, zoom: 6, tagline: "Celestial Peaks of the Tien Shan Slopes", region: "Asia" },
  { name: "Laos", code: "LA", lat: 19.8563, lng: 102.4955, zoom: 6, tagline: "Luang Prabang Monks and Gilded stupas", region: "Southeast Asia" },
  { name: "Latvia", code: "LV", lat: 56.8796, lng: 24.6032, zoom: 6, tagline: "Art Nouveau Lanes and Boreal Pine Beaches", region: "Europe" },
  { name: "Lebanon", code: "LB", lat: 33.8547, lng: 35.8623, zoom: 8, tagline: "Historic Cedar Ridges and Mediterranean Bistros", region: "Middle East" },
  { name: "Lesotho", code: "LS", lat: -29.6100, lng: 28.2336, zoom: 7, tagline: "The Mountain Kingdom in the Sky", region: "Africa" },
  { name: "Liberia", code: "LR", lat: 6.4281, lng: -9.4295, zoom: 6, tagline: "Untamed Surf Beaches and Tropical Parks", region: "Africa" },
  { name: "Libya", code: "LY", lat: 26.3351, lng: 17.2283, zoom: 5, tagline: "Ancient Roman Splendors on Mediterranean Airs", region: "Africa" },
  { name: "Liechtenstein", code: "LI", lat: 47.1660, lng: 9.5554, zoom: 10, tagline: "Charming Castles high in the Alps", region: "Europe" },
  { name: "Lithuania", code: "LT", lat: 55.1694, lng: 23.8813, zoom: 6, tagline: "The Mystical Curonian Spit Sandmass", region: "Europe" },
  { name: "Luxembourg", code: "LU", lat: 49.8153, lng: 6.1296, zoom: 8, tagline: "Deep Fortified Ravines and Modern Bankers", region: "Europe" },
  { name: "Madagascar", code: "MG", lat: -18.7669, lng: 46.8691, zoom: 5, tagline: "Fairytale Baobabs and Playful Lemurs", region: "Africa" },
  { name: "Malawi", code: "MW", lat: -13.2543, lng: 34.3015, zoom: 6, tagline: "The Warm-Hearted Lake of Golden Sand", region: "Africa" },
  { name: "Malaysia", code: "MY", lat: 4.2105, lng: 101.9758, zoom: 5, tagline: "Charming Rainforests and Sky-High Twin Towers", region: "Southeast Asia" },
  { name: "Maldives", code: "MV", lat: 3.2028, lng: 73.2207, zoom: 7, tagline: "Aquamarine Paradises and Coral Reef Bungalows", region: "Asia" },
  { name: "Mali", code: "ML", lat: 17.5702, lng: -3.9962, zoom: 5, tagline: "Legendary Gates of Mud-Brick Timbuktu", region: "Africa" },
  { name: "Malta", code: "MT", lat: 35.9375, lng: 14.3754, zoom: 9, tagline: "The Knightly Citadel of the Blue Lagoon", region: "Europe" },
  { name: "Mauritania", code: "MR", lat: 21.0079, lng: -10.9408, zoom: 5, tagline: "Sweeping Saharan Dunes and Train Deserts", region: "Africa" },
  { name: "Mauritius", code: "MU", lat: -20.3484, lng: 57.5522, zoom: 8, tagline: "Deep Sapphire lagoons and Sugar Peaks", region: "Africa" },
  { name: "Mexico", code: "MX", lat: 23.6345, lng: -102.5528, zoom: 4, tagline: "Vibrant Mariachis and Mayan Pyramids", region: "North America" },
  { name: "Moldova", code: "MD", lat: 47.4116, lng: 28.3699, zoom: 7, tagline: "Vast Wine Cellars of Milestii Mici", region: "Europe" },
  { name: "Monaco", code: "MC", lat: 43.7384, lng: 7.4246, zoom: 11, tagline: "Yacht Harbors and Grand Baccarat Palaces", region: "Europe" },
  { name: "Mongolia", code: "MN", lat: 46.8625, lng: 103.8467, zoom: 4, tagline: "The Whispering Steppes and Gobi Desert Nights", region: "Asia" },
  { name: "Montenegro", code: "ME", lat: 42.7087, lng: 19.3744, zoom: 7, tagline: "Breathtaking Fjordlands of Kotor", region: "Europe" },
  { name: "Morocco", code: "MA", lat: 31.7917, lng: -7.0926, zoom: 5, tagline: "Pastel Souks and Sweet Mint Medinas", region: "Africa" },
  { name: "Mozambique", code: "MZ", lat: -18.6657, lng: 35.5296, zoom: 5, tagline: "Sapphire Waters of the Bazaruto Archipelago", region: "Africa" },
  { name: "Myanmar", code: "MM", lat: 21.9162, lng: 95.9560, zoom: 5, tagline: "Ten Thousand Temples of Mystical Bagan", region: "Southeast Asia" },
  { name: "Namibia", code: "NA", lat: -22.9576, lng: 18.4904, zoom: 5, tagline: "Giant Apricot Dunes of the Namib Sossusvlei", region: "Africa" },
  { name: "Nepal", code: "NP", lat: 28.3949, lng: 84.1240, zoom: 6, tagline: "Mount Everest: Roof of the World", region: "Asia" },
  { name: "Netherlands", code: "NL", lat: 52.1326, lng: 5.2913, zoom: 7, tagline: "Charming Canal Mills and Rainbow Tulip Fields", region: "Europe" },
  { name: "New Zealand", code: "NZ", lat: -40.9006, lng: 174.8860, zoom: 5, tagline: "The Scenic Fiordland Middle Earth Dream", region: "Oceania" },
  { name: "Nicaragua", code: "NI", lat: 12.8654, lng: -85.2072, zoom: 7, tagline: "Volcanoes, Lagoons, and Spanish Colonial Grenada", region: "Central America" },
  { name: "Niger", code: "NE", lat: 17.6078, lng: 8.0817, zoom: 5, tagline: "Deep Tenere Desert and Nomadic Caravans", region: "Africa" },
  { name: "Nigeria", code: "NG", lat: 9.0820, lng: 8.6753, zoom: 5, tagline: "Vibrant Afrobeats and Megacities of Lagos", region: "Africa" },
  { name: "Norway", code: "NO", lat: 60.4720, lng: 8.4689, zoom: 5, tagline: "Dramatic Fjords and Aurora Borealis", region: "Europe" },
  { name: "Oman", code: "OM", lat: 21.5126, lng: 55.9233, zoom: 6, tagline: "Canyons, Castles, and Incense-Filled Bays", region: "Middle East" },
  { name: "Pakistan", code: "PK", lat: 30.3753, lng: 69.3451, zoom: 5, tagline: "The High Karakoram Hunza Peak Valley", region: "Asia" },
  { name: "Palau", code: "PW", lat: 7.5150, lng: 134.5825, zoom: 8, tagline: "Jellyfish Lake and Turquoise Rock Isles", region: "Oceania" },
  { name: "Panama", code: "PA", lat: 8.5380, lng: -80.7821, zoom: 7, tagline: "Engineering Marvels and San Blas Islands", region: "Central America" },
  { name: "Papua New Guinea", code: "PG", lat: -6.3150, lng: 143.9555, zoom: 5, tagline: "Dazzling Tribes and Bird of Paradise Forests", region: "Oceania" },
  { name: "Paraguay", code: "PY", lat: -23.4425, lng: -58.4438, zoom: 5, tagline: "Chaco Wilds and Jesuit Mission History", region: "South America" },
  { name: "Peru", code: "PE", lat: -9.1900, lng: -75.0152, zoom: 5, tagline: "Luminous Inca Path to Machu Picchu", region: "South America" },
  { name: "Philippines", code: "PH", lat: 12.8797, lng: 121.7740, zoom: 5, tagline: "Breathtaking Coral Sands of El Nido Lagoon", region: "Southeast Asia" },
  { name: "Poland", code: "PL", lat: 51.9194, lng: 19.1451, zoom: 6, tagline: "Medieval Gilded Market Halls and Pine Coasts", region: "Europe" },
  { name: "Portugal", code: "PT", lat: 39.3999, lng: -8.2245, zoom: 6, tagline: "Breathtaking Lisbon Cliffs and Pastel Tiles", region: "Europe" },
  { name: "Qatar", code: "QA", lat: 25.3548, lng: 51.1839, zoom: 8, tagline: "Futuristic Shimmer over Deep Arabian Sand Dunes", region: "Middle East" },
  { name: "Romania", code: "RO", lat: 45.9432, lng: 24.9668, zoom: 6, tagline: "Count Dracula's Spires in Dark Transylvania Forests", region: "Europe" },
  { name: "Russia", code: "RU", lat: 61.5240, lng: 105.3188, zoom: 3, tagline: "Gilded Onion Domes and Majestic Taiga Trails", region: "Europe/Asia" },
  { name: "Rwanda", code: "RW", lat: -1.9403, lng: 29.8739, zoom: 8, tagline: "The Land of a Thousand Gorilla Hills", region: "Africa" },
  { name: "Samoa", code: "WS", lat: -13.7590, lng: -172.1046, zoom: 8, tagline: "The Scenic Ocean Trench and Pristine Lagoons", region: "Oceania" },
  { name: "San Marino", code: "SM", lat: 43.9424, lng: 12.4578, zoom: 11, tagline: "Ancient Towers high on Monte Titano", region: "Europe" },
  { name: "Saudi Arabia", code: "SA", lat: 23.8859, lng: 45.0792, zoom: 5, tagline: "Mystical Hegra Tombs and Riyadh Neon Heights", region: "Middle East" },
  { name: "Senegal", code: "SN", lat: 14.4974, lng: -14.4524, zoom: 6, tagline: "Saber Rhythms and Rose-Lacquered Retba Lake", region: "Africa" },
  { name: "Serbia", code: "RS", lat: 44.0165, lng: 21.0059, zoom: 6, tagline: "Sunset Melodies over Belgrade Citadels", region: "Europe" },
  { name: "Seychelles", code: "SC", lat: -4.6796, lng: 55.4920, zoom: 8, tagline: "Granite Boulders and Coco de Mer Palm Coves", region: "Africa" },
  { name: "Sierra Leone", code: "SL", lat: 8.4606, lng: -11.7799, zoom: 7, tagline: "Golden Sandy Outposts of Freetown Surf", region: "Africa" },
  { name: "Singapore", code: "SG", lat: 1.3521, lng: 103.8198, zoom: 10, tagline: "Metropolitan Supertrees and Orchid Domelands", region: "Southeast Asia" },
  { name: "Slovakia", code: "SK", lat: 48.6690, lng: 19.6990, zoom: 6, tagline: "High Tatra Peaks and Majestic Caves", region: "Europe" },
  { name: "Slovenia", code: "SI", lat: 46.1512, lng: 14.9955, zoom: 7, tagline: "The Fairytale Emerald Lake of Bled", region: "Europe" },
  { name: "South Africa", code: "ZA", lat: -30.5595, lng: 22.9375, zoom: 5, tagline: "Majestic Safaris, Table Mountain, and Vineyards", region: "Africa" },
  { name: "South Korea", code: "KR", lat: 35.9078, lng: 127.7669, zoom: 6, tagline: "K-Wave Pulsing amidst Gilded Joseon Palaces", region: "Asia" },
  { name: "Spain", code: "ES", lat: 40.4637, lng: -3.7492, zoom: 5, tagline: "Sizzling Flamencos and Moorish Alhambra Trails", region: "Europe" },
  { name: "Sri Lanka", code: "LK", lat: 7.8731, lng: 80.7718, zoom: 7, tagline: "Sigiriya Lion Rock and Fragrant Tea Hills", region: "Asia" },
  { name: "Sweden", code: "SE", lat: 60.1282, lng: 18.6435, zoom: 5, tagline: "Sleek Archipelago Lines and Cozy Hygge Cottages", region: "Europe" },
  { name: "Switzerland", code: "CH", lat: 46.8182, lng: 8.2275, zoom: 6, tagline: "Matterhorn Glaciers and Pristine Lake Resorts", region: "Europe" },
  { name: "Syria", code: "SY", lat: 34.8021, lng: 38.9968, zoom: 6, tagline: "The Ancient Grand Bazar of Damascus", region: "Middle East" },
  { name: "Taiwan", code: "TW", lat: 23.6978, lng: 120.9605, zoom: 7, tagline: "Sizzling Night Markets and Taroko Gorge", region: "Asia" },
  { name: "Tanzania", code: "TZ", lat: -6.3690, lng: 34.8888, zoom: 5, tagline: "Mount Kilimanjaro and Zanzibar Spices", region: "Africa" },
  { name: "Thailand", code: "TH", lat: 15.8700, lng: 100.9925, zoom: 5, tagline: "Ornate Temples, Sweet Coconuts, and Sapphire Coves", region: "Southeast Asia" },
  { name: "Tunisia", code: "TN", lat: 33.8869, lng: 9.5375, zoom: 6, tagline: "Carthage Antiquities and Blue Sidibou Outposts", region: "North Africa" },
  { name: "Turkey", code: "TR", lat: 38.9637, lng: 35.2433, zoom: 5, tagline: "Where Continents Bridge: Bosphorus Wonders", region: "Europe/Asia" },
  { name: "Uganda", code: "UG", lat: 1.3733, lng: 32.2903, zoom: 7, tagline: "Source of the Nile and Mountain Chimpanzees", region: "Africa" },
  { name: "Ukraine", code: "UA", lat: 48.3794, lng: 31.1656, zoom: 5, tagline: "Charming Cobblestones of Lviv Heritage", region: "Europe" },
  { name: "United Arab Emirates", code: "AE", lat: 23.4241, lng: 53.8478, zoom: 7, tagline: "Sky-High Mirages out of Golden Dessert Dunes", region: "Middle East" },
  { name: "United Kingdom", code: "GB", lat: 55.3781, lng: -3.4360, zoom: 5, tagline: "Royal Castles, Rolling Highlands, and Cosy Pubs", region: "Europe" },
  { name: "United States", code: "US", lat: 37.0902, lng: -95.7129, zoom: 4, tagline: "Skyline Lights, Grand Canyons, and Endless Horizons", region: "North America" },
  { name: "Uruguay", code: "UY", lat: -32.5228, lng: -55.7658, zoom: 7, tagline: "Sophisticated Sunsets at Punta del Este", region: "South America" },
  { name: "Uzbekistan", code: "UZ", lat: 41.3775, lng: 64.5853, zoom: 6, tagline: "Lapis Lazuli Domes on the Golden Road", region: "Asia" },
  { name: "Vatican City", code: "VA", lat: 41.9029, lng: 12.4534, zoom: 12, tagline: "Grandeur of St. Peter's Dome", region: "Europe" },
  { name: "Venezuela", code: "VE", lat: 6.4238, lng: -66.5897, zoom: 5, tagline: "The Towering Majesty of Angel Falls", region: "South America" },
  { name: "Vietnam", code: "VN", lat: 14.0583, lng: 108.2772, zoom: 5, tagline: "Emerald Karsts of Halong Bay", region: "Southeast Asia" },
  { name: "Yemen", code: "YE", lat: 15.5527, lng: 48.5164, zoom: 5, tagline: "Skyscrapers of Mud-Brick Shibam", region: "Middle East" },
  { name: "Zambia", code: "ZM", lat: -13.1339, lng: 27.8493, zoom: 5, tagline: "The Thundering Smoke of Victoria Falls", region: "Africa" },
  { name: "Zimbabwe", code: "ZW", lat: -19.0154, lng: 29.1549, zoom: 5, tagline: "Mana Pools Safari and Ancient Granite Ruins", region: "Africa" }
];
